### ISSUE TITLE
Custom Widgets (barrating and select2) properties not updated in JSON Editor

### ISSUE THREAD

**Issue by muhfred** [surveyjs/editor#106]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

- In barrating custom widget: everything is fine except that `"ratingTheme":"fontawesome-stars"` property isn't updated in JSONString, and I need it so that it gets rendered when the survey is published.

 - In select2 custom widget: I need the property `"renderAs":"select2"` in JSON Editor when adding the question so that it gets rendered when the survey is published.
 

### What is the expected behavior?
 - `"ratingTheme":"fontawesome-stars"` property to be updated and written in  JSON Editor when adding the question barrating, so that it gets rendered when the survey is published.

 - `"renderAs":"select2"` property to be updated in  JSON Editor when adding the question "Dropdown", so that it gets rendered when the survey is published.

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/e7GgwcYJudAbeC7hNmdg?p=preview

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome latest version
* editor version: 0.12.17
* surveyjs version: 0.12.17

**Comment by muhfred** [comment]
@andrewtelnov thank you for your work, did you get a chance to at this issue?
Thanks.

**Comment by andrewtelnov** [comment]
@muhfred 1) "ratingTheme":"fontawesome-stars" doesn't save because it is the default value. Please look at the code. 
Registering the property, the default value is "fontawesome-stars":
`Survey.JsonObject.metaData.addProperty("dropdown", {name: "ratingTheme", default: "fontawesome-stars", choices: ["fontawesome-stars", "css-stars", "bars-pill", "bars-1to10", "bars-movie", "bars-square", "bars-reversed", "bars-horizontal", "bootstrap-stars", "fontawesome-stars-o"]});`
Then in the widget code:
If ratingTheme is not defined, use the the "fontawesome-stars"
`      var ratingTheme = question.ratingTheme ? question.ratingTheme : "fontawesome-stars";`
2) Please add this property, as shown in the example:
`Survey.JsonObject.metaData.addProperty("checkbox", {name: "renderAs", default: "standard", choices: ["standard", "select2"]});`
and then update the isFit method as:
` isFit : function(question) { return question.getType() === 'checkbox' && question["renderAs"] === 'select2'; },`

Thank you,
Andrew

**Comment by muhfred** [comment]
@andrewtelnov I did what you suggested, JSON Editor is just not updated, please checkout the plunker : [https://plnkr.co/edit/e7GgwcYJudAbeC7hNmdg?p=preview](url) 
All I want is that the barrating property "ratingTheme" to be set to "fontawesome-stars" in JSON Editor when adding the barrating question, and the same for dropdown question property "renderAs" : "select2" to be set in JSON Editor when adding a dropdown question. How I can do this?
Thank You.

**Comment by andrewtelnov** [comment]
I have made two modification, take a look at //!!!
https://plnkr.co/edit/nM7pQeI1YNqfb7ci6jZ5?p=preview

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@muhfred We fully re-write our custom widgets support, https://surveyjs.io/Examples/Library/?id=custom-widget-select2-tagbox

Thank you,
Andrew
