### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by AJF4** [surveyjs/editor#191]
### Are you requesting a feature, reporting a bug or ask a question?

Question - does editor already support Bootstrap 4? If not, are there plans to introduce this?

**Comment by andrewtelnov** [comment]
@AJF4 It is definately in our radar. We are busy with the release at the current moment. We are going to release v1.0 is several weeks.
After the initial v1.0 we will work on Bootstrap 4.

Thank you,
Andrew

**Comment by AJF4** [comment]
Thanks, do you have an idea of timeframe? (both for the 1.0 release and for the BS4 update?) 

If BS4 is likely to be shortly after the 1.0 release then I can defer my integration work until it's complete - if it's going to be months, then I may be better taking the pain of keeping the rest of the project on BS3. 

Thanks, 

A

**Comment by andrewtelnov** [comment]
@AJF4 I hope we will release v1.0 in three weeks, https://surveyjs.answerdesk.io/internal/ticket/details/T233 
I would say BS4 has the highest priority, since it has been asked several times already. However, I would not rely on us on 100%.
It is very likely that we will introduce it by the end of the year, but we have not done any investigation yet, and if during implementation we find that it is difficult to implement, we may postpone it. So, it is very unlikely, there will be any difficulties in implementation.

Thank you,
Andrew

**Comment by AJF4** [comment]
Thanks @andrewtelnov - good luck with the releases!

**Comment by tsv2013** [comment]
@AJF4 We've introduced Bootstrap 4 support since v0.96.2 (https://github.com/surveyjs/editor/releases/tag/v0.96.2).

**Comment by AJF4** [comment]
Wow - that's awesome @tsv2013 - thank you! 

I'll do the upgrade in our project tomorrow and let you know how it goes. 

thanks again. 

A

**Comment by SamMousa** [comment]
@tsv2013 the surveyjs-editor NPM package doesn't support bootstrap 4 due to its version constraints:
https://github.com/surveyjs/editor/blob/master/package.json
