### ISSUE TITLE
Introduce "Visible If" wizard

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/editor#281]

**Comment by andrewtelnov** [comment]
@tsv2013 @dmitrykurmanov Instead of wizard, I have added a three inputs and button on the top that adds the condition.
The work doesn't finish yet.
Unfinished tasks:
* remove the current question from the list
* add items into question select for complex questions
* optionally use select2 if it is available

**Comment by andrewtelnov** [comment]
It would be cool to show the question for setting the value. I will add it to the task.
