### ISSUE TITLE
Bug : Missing localization strings in the master template

### ISSUE THREAD

**Issue by fastclemmy** [surveyjs/editor#299]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

When using a localized version of the SurveyJS builder, some items miss their localized text, [see the localization example](https://surveyjs.io/Examples/Editor/?id=localization).

**Question**

- Click to add an item...

**Question properties**

- none
- correctAnswer
- defaultValue
- description
- enableIf
- page
- readOnly
- requiredErrorText
- titleLocation
- default
- top
- bottom
- left
- hidden
- valueName
- visible

**Survey properties**

- completedBeforeHtml
- firstPageIsStarted
- isSinglePage
- loadingHtml
- maxTimeToFinish
- maxTimeToFinishPage
- questionErrorLocation
- questionsOrder
- initial
- random
- showPrevButton
- showTimerPanel
- showTimerPanelMode
- startSurveyText

(may have missed some hidden in the GUI, is there a way to automate this to check?)

### What is the expected behavior?

All the strings should be in [the master template](https://github.com/surveyjs/editor/blob/master/src/editorLocalization.ts). Right now, I can see several keys are missing.

AND some of the keys above are both in the master template and in the French localization file but they still don't get translated (e.g. showTimerPanel, showTimerPanelMode, defaultValue...) => bug?

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Examples/Editor/?id=localization

* browser: Firefox 58
* editor version: 1.10.13

**Comment by andrewtelnov** [comment]
@fastclemmy 
1) pe.addItem: "Click to add an item..." - it is localized
2) default, top, bottom, left, hidden - they have defaultStrings.pv.[valueName]. We do not have them, because if the property value is not localized then its origional name is used, bottom is bottom and top is top. Names are fine by default. You may add them next to the     `true: "true", false: "false",`.
3) other properties should go to defaultStrings.p.[propertyName], again you may localize them and the localized version will be used and not the origional propertyName.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@fastclemmy We will include all names, even they are not nessassary for the English version. It will help with translation.

**Comment by andrewtelnov** [comment]
Additonally, put the default (en) localization into separate file _default.ts into "localization" folder.
