### ISSUE TITLE
Restrict Item Values to Numeric Values

### ISSUE THREAD

**Issue by nrhoffmann** [surveyjs/editor#350]
### Are you requesting a feature, reporting a bug or ask a question?
I am asking a question / requesting a feature.

### What is the current behavior?
Currently, there are no restrictions on the value of matrix, dropdown, and radiogroup question items.
At least I think.

### What is the expected behavior?
It would be cool -- also super helpful -- if I could restrict values to only numeric values. Or perhaps add validation so the user could only set the value to something thing that passes a specified regex.

**Comment by tsv2013** [comment]
You can set numeric values for items, e.g.
```JS
{
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "radiogroup",
     name: "question1",
     choices: [
      {
       value: 1,
       text: "Text 1"
      },
      {
       value: 2,
       text: "Text 2"
      },
      {
       value: 3,
       text: "Text 3"
      }
     ]
    }
   ]
  }
 ]
}
```

Probably I havn't understood your scenario. Could you explain it in greater details?

**Comment by nrhoffmann** [comment]
I didn't know you could do that. 

But, that still doesn't full solve the problem...
I my application we use the value property to hide some magic number behind the text. We want to allow the users to set that value to what number that want. That's why we don't just remove the value from the question editor and set it automatically with the `onItemValueAdded`. But, if the user sets the value to something and our back-end cannot parse a double out of it our system breaks. (In a previous version of our system, value could be a string, but could not contain spaces.) In our application restricting values to doubles makes sense, so its not something we plan on changing.

This got me thinking... maybe there could be some validation on blur, and the question editor wouldn't save if there was an error.

![capture](https://user-images.githubusercontent.com/24707041/41047187-fca4bfe0-6979-11e8-8e24-f88b89f7768f.PNG)

I think that this might be best implemented with a regex for validation and a custom error message.

**Comment by andrewtelnov** [comment]
@nrhoffmann I have just fixed [the bug](https://github.com/surveyjs/editor/issues/351). Because of this bug the event onPropertyValidationCustomError doesn't called for editors in the Value column.
The fix will be available in the next version. You may build the sources by yourself.
Here is the code that you will have to use:
```
editor.onPropertyValidationCustomError.add(function (editor, options) {
    if (options.propertyName !== "value") return;
    if (!options.obj && (!options.obj.getType || options.obj.getType() !== "itemvalue")) return;
    if (isNaN(Number(options.value))) {
        options.error = "Please enter numeric value";
    }
});
```

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@nrhoffmann I was playing with an example to update the documentation. You may optional show/hide the error on changing the value in cell editor. It means end-user will show error without pressing Apply or OK buttons. Here is the updated code:
```
function isItemValueObj(obj) {
    return obj && obj.getType && obj.getType() == "itemvalue";
}
editor.onPropertyValueChanging.add(function (editor, options) {
    if (options.propertyName !== "value" || !isItemValueObj(options.obj)) return;
    options.doValidation = true;
});
editor.onPropertyValidationCustomError.add(function (editor, options) {
    if (options.propertyName !== "value" || !isItemValueObj(options.obj)) return;
    if (isNaN(Number(options.value))) {
        options.error = "Please enter numeric value";
    }
});
```
Thank you,
Andrew

**Comment by leksinteractive** [comment]
One more related question @andrewtelnov @tsv2013 ,

How would you implement validation to make sure that each value in the options is unique?

It seems onPropertyValidationCustomError is called individually for each option, so there isn't a way to evaluate the options for duplicates in an obvious way. If you have any ideas on this it would be much appreciated.

I imagine this is a common scenario because if we let the user enter the same value more than once, we are not able to distinguish the exact value the user has selected when filling out the survey. eg. we get the responses in the format { value: answer }, so there's no way to know which 'value' was selected if there's more than 1 occurrence of it.

Thanks again.

**Comment by ouakib** [comment]
@andrewtelnov Can we initialize values with 1,2.. instead of item1,item2.. ?

**Comment by andrewtelnov** [comment]
@ouakib It shows in [this example](https://surveyjs.io/Examples/Survey-Creator?id=toolboxcustomization).

Thank you,
Andrew

**Comment by ouakib** [comment]
It works but when I create a new value it is initialized with item1 and not a numeric value

**Comment by andrewtelnov** [comment]
@ouakib Please create a new issue here.

Thank you,
Andrew

**Comment by ouakib** [comment]
@andrewtelnov If I delete all the itemvalues and then create a new one how to assign automtically a value ?
