### ISSUE TITLE
Set Editor Properties Value

### ISSUE THREAD

**Issue by cracki** [surveyjs/editor#354]
How i can set Property value?

For example i want to set "showQuestionNumbers" to "off" by default

Survey.JsonObject.metaData.findProperty("survey", "showQuestionNumbers")

How to set it?
Thank you

**Comment by andrewtelnov** [comment]
@cracki 
`Survey.JsonObject.metaData.findProperty("survey", "showQuestionNumbers").default = "off";`
However, it would only tells survey do not serialize showQuestionNumber with property "off". 
You must to override the getter of the showQuestionNumbers property. It can be done, thanks to JavaScript magic. Here is [the example](https://plnkr.co/edit/MogEFRTbx69BrVDX5vr7?p=preview)

**Comment by cracki** [comment]
thank you
i want to set "off" the value in editor mode.

default = "off" not worked

**Comment by andrewtelnov** [comment]
Sure, I wrote it would not work. You have to override getter. Have you copied the code for overriding property in plunker I gave?

Thank you,
Andrew

**Comment by cracki** [comment]
yes i copy plunker codes
i get:
"TypeError: this.getPropertyValue is not a function"

**Comment by andrewtelnov** [comment]
@cracki It works fine for me, here is the [form bulder example](https://plnkr.co/edit/6x3MIgTN0BYM8wqXNbbF?p=preview)

Thank you,
Andrew

**Comment by cracki** [comment]
Thank You 👍

**Comment by irshadnilam** [comment]
Hi @andrewtelnov 
Hi, I am following [this](https://github.com/surveyjs/surveyjs_react_quickstart) example to integrate editor with React.  

And I want to hide question number like @cracki wanted. I couldn't get it working using the plunker example because 'Survey' object is not defined in the component. 

I tried to import Survey from 'survey-react'. But it didn't do the trick. Can you tell me what am I missing here?

Thanks

**Comment by irshadnilam** [comment]
@andrewtelnov I am using that repo as I've mentioned above.  I want to achieve what the original poster did using react.
