### ISSUE TITLE
JSON specify class/id

### ISSUE THREAD

**Issue by frankwo1** [surveyjs/editor#398]
### Are you requesting a feature, reporting a bug or ask a question?

feature
Hi Andrew,
I was wondering if it is possible to add a class selector or id selector in the Editor JSON 
I think this would solve a lot of the CSS issues that people ask about
Something like this:
Test code

```
	    {
	     "type": "radiogroup",
	     "name": "S1",
	     "title": "What is your gender?",
	     "isRequired": true,
       "class": "col-sm-6",
	     "choices": [
	      {
	       "value": "1",
	       "text": "Male"
         "class": "col-sm-2",
	      },
	      {
	       "value": "2",
	       "text": "Female"
         "class": "col-sm-2",
	      }
	     ],
	     "colCount": 2
	    },

```

**Comment by andrewtelnov** [comment]
@frankwo1 You can implement it for your own project.
Add properties, [here is documenation](https://surveyjs.io/Documentation/Builder/#addproperties)
```
Survey.JsonObject.metaData.addProperty("questionbase", { name: "class" });
Survey.JsonObject.metaData.addProperty("itemvalue", { name: "class" });
```
and the use onAfterRenderQuestion event to set them into the element. Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-afterrender)

We do not want to introduce the rendering definition as classes into survey. Non-technical people will never understand it and software developers will implement it with several lines of code in the way they need it.

Thank you,
Andrew

**Comment by frankwo1** [comment]
Hi Andrew, Thanks, I respectfully disagree - even those with "soft programming skills" "HAVE TO" work with SurveyJS Editor JSON file (e.g. set up conditions, filters, etc.). By limiting to JS, you are limiting usage only to those who have a degree of programming skills. By adding classes/IDs into the forms, you now allow web developers to use HTML/CSS to render qs (a much larger group of users) Would be interesting to conduct a survey among your users to find out who uses it (can I help?).
Respectfully,
Frank

**Comment by andrewtelnov** [comment]
@frankwo1 You raised an interesting question indeed. We have discussed the similar features here internally as well. I would like to explain the decision in more details.
Here is my position based on over 20 years’ experience of making libraries for developers. I could not say that I am right, and others are wrong. It is just my position :)
There are two ways of solving these issues:
a)	Add all possible functionalities into your library
b)	Make your library flexible enough to let developers extend the library and add the functionality they need.
All these solutions have Pros and Cons. Sometimes it makes sense to introduce the functionality into the library, sometimes it makes sense to let developers/your users introduce the functionality by themselves. You can’t add into library all possible features, since it would become a mess that nobody want to use.
Regarding introducing “class” property. As soon as we introduce this property into survey definition in the core library, it is not hard to do, survey definition will become depended from web sites, from styles. The logic functionality like visibleIf and enableIf would work absolutely the same on any website. This “class” property is not that case. I would not like to have “class” property in our Survey Service implementation. I don’t want to let our end-users know about styles we have on our web site. I would rather add markup support on our web site, that we already have. So, an end-user could write: “<strong>{Name}</stroing>” in a markup Editor.
Additionally, by introducing this functionality in the core would mean that we should support it in all platforms we support now and in platforms that we will support in the future, including, for example, react native.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@frankwo1 Of course. Anyway, thank you for you feedback and opinion. 

Thank you,
Andrew
