### ISSUE TITLE
Styling the editor is impossible 

### ISSUE THREAD

**Issue by sylv3r** [surveyjs/editor#445]
I tried to create a decent styling for the editor, replacing the default one, but that's basically impossible.

- Lot of duplicate styling definitions overriding each other or defining the same style over and over
- inline styling in the js script which makes it impossible to not import it
- nearly all definition use `!important` which makes overriding them impossible too

Is there any way to remove these styling and be able to apply our own style ? (maybe a hidden feature ?)

**Comment by tsv2013** [comment]
SurveyJS has pre-defined themes with customizable options. Here is the sample from our site - https://surveyjs.io/Examples/Builder/?id=editor-custom-theme&theme=bootstrap

Does it fit your needs?

Could you please specify - what exact customizations do you want to do?

**Comment by tsv2013** [comment]
At this moment I see the only problem with styling - our CSS selectors are too long due to using nested styling in SCSS.

There are the following available options for customization:
- use the built-in themes engine
- write a longer selectors for custom styles
- recompile the whole styles - https://github.com/surveyjs/editor/blob/master/src/main.scss

If you share your scenario I can check how does it fit current markup of the editor and how we can improve the situation.

**Comment by sylv3r** [comment]
I don't even include your css.

The main problem is the styling hard-coded with `!important` in here https://github.com/surveyjs/editor/blob/master/src/stylesmanager.ts

**Comment by tsv2013** [comment]
As far as I remember this "!important" should work for bootstrap themes only due to bootstrap uses "!important" inside bootstrap code. If you will use "default" or other non-bootstrap theme it should work ok.
But now I haven't found BS importants we're overriding.

We'll remove these "!importants" - it's not a problem

**Comment by tsv2013** [comment]
@sylv3r  BTW - if you switch to default theme, these importants will not be injected:
```JS
SurveyEditor
    .StylesManager
    .applyTheme("default");
```

**Comment by sylv3r** [comment]
Is bootstrap the default theme ? I didn't choose one explicitly (don't even know how to do that), and there's nothing about choosing a theme in your sample editor code integration.

**Comment by tsv2013** [comment]
> Is bootstrap the default theme ?

Yes for editor (builder)

**Comment by sylv3r** [comment]
Ok, thanks, I will try with that

**Comment by sylv3r** [comment]
That works, thanks !

(btw, I don't see any visual difference between the `bootstrap` and `default` theme, else than resolving my problem, is this expected ?)

**Comment by tsv2013** [comment]
At the very beginning the editor had the only theme - bootstrap. But it was highly customized and sometimes we struggled to overcome bootstrap styles. After we'd implemented themes for editor, we leave the bootstrap default theme for the backward compatibility. But the default theme is almost the same as bootstrap.
Probably is was not the best decision.

**Comment by sylv3r** [comment]
Ok, got it. Thanks for your help !

Yeah, legacy, we all have to deal with it at some point ;)

**Comment by dmitrykurmanov** [comment]
Anyway we have some wrong css rules with `!important` because of material-bootstrap. Removed it.
