### ISSUE TITLE
SurveyJS 1.0.49 editor JSON not compatible with version 1.0.56

### ISSUE THREAD

**Issue by lukasmedia** [surveyjs/editor#449]
### Are you requesting a feature, reporting a bug or ask a question?

Bug, i guess.

### What is the current behavior?

The JSON from the 1.0.49 builder does not render the elements in the 1.0.56 builder.
JSON: https://pastebin.com/R3gn5854

### What is the expected behavior?

The JSON should render a "preview" form in the form builder.

### How would you reproduce the current behavior (if this is a bug)?

Run the 1.0.49 builder, paste the JSON (see pastebin above) in JSON Editor.
Verify the form in the builder (click Survey Designer).
Run the 1.0.56 builder. Paste the JSON in JSON editor.
You cannot click Survey Designer. 

Console.log: TypeError: e.getValueName(...).toLowerCase is not a function

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: see https://surveyjs.io/Survey/Builder 
I have a 1.0.49 running on local host.

Test code: https://pastebin.com/R3gn5854

### Specify your

* browser: any.
* editor version: see above.

**Comment by andrewtelnov** [comment]
@lukasmedia  The bug has been fixed by [this commit](https://github.com/surveyjs/surveyjs/commit/db2ef271a4f3605f4cd78136d3fd8c830d2114be)
Unit test has been added. We will release a new version with the fix on the next week.
As a work-around you may change the valueName from numeric to string value.
The bug has been introduced by using hash with lowcase valueNames for improving perfomance on calling getQuestionByValueName. Before it go through all questions and check the valueName/name, now it calls the hash function.

Thank you,
Andrew
