### ISSUE TITLE
Question: Regarding platform support

### ISSUE THREAD

**Issue by hyndsite** [surveyjs/editor#48]
Your homepage lists for the editor: 

> Currently only knockout version is ready.
> Versions for other platforms (react, Angular, jQuery) are coming.

Any idea of a timeline when any other (any of those listed above) are expected to be released?

**Comment by andrewtelnov** [comment]
@hyndsite To be honest we have postponed this task some time ago. At least for a couple months. I have spent several days on this task in early January, understood the amount of work and we decided to comeback to this later. We have a huge TODO list and this feature went down, since the cost of implementing it is high.
Another reason: knockout works perfectly with all other platforms and it is 22kb in gz. As we found, it  is not that a big deal for the most developers.
Do you have any issue with knockout in your current project?

PS: Probably, we should to remove this statement. We do not know exactly how bad do we need react/jquery versions.

Thank you,
Andrew

**Comment by hyndsite** [comment]
Thanks @andrewtelnov for the quick response.

Its being consider for a project and wanted to know the scope of options before a direction is chosen.  

It sounds like you're saying that there are React or Angular projects implementing the KO visual editor without issues then?

Thanks again.

**Comment by andrewtelnov** [comment]
@hyndsite you should not have problems: http://www.intelligiblebabble.com/making-reactjs-and-knockoutjs-play-nice
Additionally, you will likely use SurveyJS Editor as external widget. By the way, if you have any issues, we are here to help. 

Thank you,
Andrew

**Comment by hyndsite** [comment]
Thanks for the info.
