### ISSUE TITLE
Custom Properties should also appear in the Settings Modal

### ISSUE THREAD

**Issue by we-CONECT-Joe** [surveyjs/editor#56]
currently, custom properties only show up in the "Property window" to the right, but not yet in the settings modal.

I first expected them to be there too, but later found them by accident ;)

can be seen here: http://editor.surveyjs.io/examples/addproperties.html 
"tag" is only in the property window but not in the question edit modal popup

best,
Joe

**Comment by andrewtelnov** [comment]
@we-CONECT-Joe Hm.. I have thought about this code today. I was not happy with the code we have in the question editor (modal window). I have introduced the readOnly attribute in the JsonProperty and wanted to make the inputs in modal window read-only if the attribute is set. I have realized it is a lot of work and code should be re-written. 
I think, I will be able to give the ability to modify (add/remove) properties in the question editor (modal windows) as well. 
I have just added it in out TODO list. And since it makes sense to implement it together with read-only properties support, I think we can implement it in a week or so.

Thank you for good idea! 
Andrew

**Comment by andrewtelnov** [comment]
@we-CONECT-Joe It is implemented. Please take a look at [the following demo](http://editor.surveyjs.io/examples/questioneditor.html) and read the description

**Comment by andrewlphilpott** [comment]
The demo linked above seems to have been removed. Is there a working demo anywhere?

**Comment by andrewtelnov** [comment]
@andrewlphilpott Here is [the example](https://surveyjs.io/Examples/Survey-Creator/?id=questioneditor) and here is [the doc](https://surveyjs.io/Documentation/Survey-Creator/#elementseditor).

Thank you,
Andrew

**Comment by andrewlphilpott** [comment]
This example looks like it only shows how to put question properties in the question modals. I'm looking for a way to put survey properties in the modal that pops up when you click the Survey Settings button. Is that documented anywhere?

**Comment by andrewtelnov** [comment]
@andrewlphilpott It is the same. Just use "survey" instead of "question".

```js
Survey.Serializer.addProperty("survey", "tag");
var editorDefinition = SurveyCreator.SurveyQuestionEditorDefinition.definition["survey"];
editorDefinition.properties.push({name: tag});

```

**Comment by andrewlphilpott** [comment]
@andrewtelnov Thanks!
