### ISSUE TITLE
Add custom properties to Matrix Rows.

### ISSUE THREAD

**Issue by we-CONECT-Joe** [surveyjs/editor#57]
It would be nice to have the ability to add custom properties to Matrix rows. 

It would open up the way to proper answer categorization =)

best,
Joe

**Comment by andrewtelnov** [comment]
@we-CONECT-Joe Could you please describe your scenario? I am not sure about this feature since I can not understand how to make it generic and not hard-coded at the current moment. What UI do you have in mind?

Thank you,
Andrew

**Comment by we-CONECT-Joe** [comment]
Well simply put every row in a matrix question represents a common "topic".

Lets say an example would be cars and we have the following table:

What are your favorite cars?
Lable  |  How much do you like it | have you driven one |  did you ever own one
Mercedes | 5 Stars | Yes | Yes
BMW | 4 Stars | Yes | No

Ok so fare so good,  each of the rows, represent an Answer for the Cars, which are my favorites because i answered anything in their row.

The Info i want to pull from that is:
- Get Users rows that have been answered, put them into context:
 - Mercedes [rated: 5 stars; driven:yes owned: yes;], BMW[rated:  4 stars; driven:yes owned: no;]

Basically:
- Matrixes: Question gives Category as Tag "favorite Cars"
		- Rows have their own tags  "BMW"


The way i see it, a matrix row is a "tag" or a "category" or a "group" however you will for each column in the row and thus, i would like to add custom property to the row, multiple actually.
For one, i would like to add a tag (so in the backend i can process the results by tag later), on the other side, an id would also not be bad. in anyway a Matrix row must represent more than key, value.

` rows: [
      "Mercedes",
      "BMW"
     ]`

should become
` rows: {
    "Mercedes Benz" {
       name: , 
id:"xxy",
tag:"Mercedes"

      },
     }`

Litreally everything else is an object too =)

**Comment by andrewtelnov** [comment]
@we-CONECT-Joe. I think you are talking about Dropdown matrix question. Rows is the array of ItemValue.
You may use it in json as "Mercedes" or {value: "Mercedes", text: "Mercedes Benz"}
If text is undefined, it uses the value.
ItemValue is a generic class in SurveyJS. It uses it many other questions, for example dropdown and radio group (choices property).
In fact ItemValue supports custom attributes already. You may have:
{value: "Mercedes", text: "Mercedes Benz", id: "xxy"}. 
SurveyJS will be able to read this json and you will have the id attribute. 
However, If you edit this json in the Editor, it will remove this attribute on save, since it doesn't know about it.
I may probably be able to add the code that will not remove these attributes on saving, but to change them in the Editor, you will have to register your own Property Editor.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@we-CONECT-Joe I know it is late. However there is an ability to add this property into the designer by writting two lines of code. Here is [the example](https://plnkr.co/edit/gU88CL?p=preview)

Thank you,
Andrew

**Comment by Wenzil** [comment]
This solution doesnt seem to work with the latest version

**Comment by andrewtelnov** [comment]
@Wenzil You are right. I will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Wenzil I have updated [the example](https://plnkr.co/edit/WgF18IEAc708RPHXuQG8?p=preview) to the latest version.

Thank you,
Andrew
