### ISSUE TITLE
Pagination and Loading Capability

### ISSUE THREAD

**Issue by hyndsite** [surveyjs/editor#60]
Currently, it appears that survey's can be sectioned by the use of pages, but it still requires all pages, questions (the entire survey) when loading the survey.  

Is there any capability (or future plan) of allowing survey.js to load only a "page" of a survey, and make subsequent calls for additional pages when needed?

**Comment by andrewtelnov** [comment]
@hyndsite As I understand, there is a logic on the server, that generate pages and questions based on the answers, am I right?
Why don't you want to include the logic on the client? You may make the page/question visible/invisible by using visibleIf page/question property.
surveyjs should work with pretty large surveys. I have not seen surveys that has a performance issue. If there are these surveys, I would love to look at them and I am pretty sure, that I will be able to fix the performance issues.
To be honest, the reason I have started the surveyjs, because I was not be able to find a good client JavaScript survey library. All these client-server solutions, based on 10-15 years old technologies, looks pretty odd in the modern web app.
The client computers are powerful these days and IMHO, it is not the great idea to keep the server busy with client tasks.

Anyway, of course, there is maybe a good reason for this functionality. In this case, please describe your scenario.

Thank you,
Andrew

**Comment by hyndsite** [comment]
Unfortunately, though it might not have surfaced yet, there will be that client corner case where they push the boundaries of question count.

But fortunately, from what I see in the current base code, is that survey.js will take (valid) json that makes up a survey, without actually knowing if it is the entire survey.  So if your server side code renders JSON that is only part of the survey (e.g. page 1) with all the required JSON to make up of a survey.js survey, it wouldn't know the difference.

**Comment by andrewtelnov** [comment]
@hyndsite Forgot to mention. If you decided to try to go this way, then these properties you may find useful:
survey.questionStartIndex - you may set it to 28, so the first question will be the 28.
survey.pageNextText, survey.pagePrevText and survey.completeText - the text of corresponded buttons.
Events: onCurrentPageChanged, onComplete.

Thank you,
Andrew
